import type { Metadata } from 'next';
import { ThemeProvider } from '@mui/material';
import Background from 'components/Background';
import DefaultTheme from 'styles/themes';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider theme={DefaultTheme}>
      <html lang="en">
        <body>
          <Background
            starCount={5000}
            starColor={[255, 255, 255]}
            speedFactor={0.05}
            backgroundColor="black"
          />
          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
